<?PHP
/**
 *  SuperParser - a custom xss parser
 *  
 *  Requires:
 * 	  Parsedown: http://parsedown.org/
 * 	  Parsedown Extra: https://github.com/erusev/parsedown-extra
 * 	  ParsedownFilter: https://github.com/Chris--A/ParsedownFilter
 * 		Note: You will want to uncomment his ParsedownFilterExtra class
 * 	  Oembed: A private library.
 * 	  simple_html_dom: http://simplehtmldom.sourceforge.net/
 *
 * 	Usage:
 * 	  $parser = new SuperParser();
 * 	  $newContent = $parser->parse($content);
 *
 *  Contact:
 *    Blake Patton - blake[at]blakethepatton[dot]com
 * 	
 */
class SuperParser
{
	private $mdParser;
	private $html;
	private $autoEmbed;
	private $images;
	private $links;
	private $input;
	
	/**
	 * [__construct Initializes variables]
	 */
	public function __construct(){
		$this->mdParser = new ParsedownFilterExtra( array($this, 'filter') );
		$this->autoEmbed = new App\Libraries\AutoEmbed();
		$this->html = new simple_html_dom();
		$this->images = array();
		$this->links = array();
	}

	/**
	 * [parse Runs before, parser and after]
	 * @param  [string] $input [Non sanitized input with MD formatting]
	 * @return [string]        [sanitized input with html formatting]
	 */
	public function parse($input){
		$this->input = $input;
		$this->before();
		$this->parser();
		$this->after();
		return $this->input;
	}

	/**
	 * [filter Helper function for adding rel and target tags]
	 * @param  [array] &$el [Populated from within ParsedownFilter]
	 * @return [null]       [nothing]
	 */
	public function filter(&$el){
		switch( $el[ 'name' ] ){
	    	case 'a':
	            $url = $el[ 'attributes' ][ 'href' ];

	            /***
	                If there is no protocol handler, and the link is not an open protocol address, 
	                the links must be relative so we can return as there is nothing to do.
	            ***/

	            if( strpos( $url, '://' ) === false )
	                if( ( ( $url[ 0 ] == '/' ) && ( $url[ 1 ] != '/' ) ) || ( $url[ 0 ] != '/' ) ){ return; }


	            if( strpos( $url, $_SERVER["SERVER_NAME"] ) === false ){
	                $el[ 'attributes' ][ 'rel' ] = 'nofollow';
	                $el[ 'attributes' ][ 'target' ] = '_blank';
	            }
	            break;
    	}
	}

	/**
	 * [before Runs before markdown gets parsed]
	 * 	 This function turns html a and img tags into their markdown equivalent.
	 * @return [string] [markdown formatted string]
	 */
	private function before(){
		$html = $this->html->load($this->input, true, false);

		// convert html links to md flavored links
		$a = array(); //save original element info
		if(count($html->find('a'))>0){
		    foreach($html->find('a') as $e){
		        $url   = (isset($e->href)) ? $e->href : '';
		        $text  = (isset($e->innertext)) ? $e->innertext : $url;
		        $class = (isset($e->attr['class'])) ? trim($e->attr['class']) : '';
		        $id    = (isset($e->attr['id'])) ? trim($e->attr['id']) : '';

		        //setup the class
		        $class = str_replace(' ', ' .', $class);
		        $class = (strlen($class)>0) ? '.'.$class : null;
		        //setup the id
		        $id    = (strlen($id)>0) ? '#'.$id : null;

		        $new = "[".$text."](".$url.")";

		        if($class!=null || $id!=null){
		            $new .= ' {'.trim($class.' '.$id).'}';
		        }        

		        $a[] = array('new'=>$new, 'original'=>$e->outertext);
		        $e->outertext = $new;
	    	}
	    	unset($e);
		}

		// convert html img tags to md flavored img tags

		$img = array(); //save original element info
		if(count($html->find('img'))>0){
		    foreach($html->find('img') as $e){
		        $url   = (isset($e->attr['src'])) ? $e->attr['src'] : '';
		        $text  = (isset($e->attr['alt'])) ? $e->attr['alt'] : '';
		        $class = (isset($e->attr['class'])) ? trim($e->attr['class']) : '';
		        $id    = (isset($e->attr['id'])) ? trim($e->attr['id']) : '';

		        //setup the class
		        $class = str_replace(' ', ' .', $class);
		        $class = (strlen($class)>0) ? '.'.$class : null;
		        //setup the id
		        $id    = (strlen($id)>0) ? '#'.$id : null;

		        $new = "![".$text."](".$url.")";

		        if($class!=null || $id!=null){
		            $new .= ' {'.trim($class.' '.$id).'}';
		        } 
		        
		        $img[] = array('new'=>$new, 'original'=>$e->outertext);
		        $e->outertext = $new;
		    }
		    // save on resources.
		    unset($e);
		}

		$this->links  = $a;
		$this->images = $img;
		$this->input = $html;
		return $html;
	}

	/**
	 * [parser Runs the parser to convert markdown into html]
	 * @return [string] [html formatted string]
	 */
	private function parser(){
		$this->input = $this->mdParser->setMarkupEscaped(true)->parse($this->autoEmbed->parse($this->input));
		return $this->input;
	}

	/**
	 * [after Runs after the parser to clean up any non-parsed MD generated by the before method.]
	 * @return [string] [html formatted string]
	 */
	private function after(){
		// now that all the images and links are generated... restore non-markdownified with their old content.
		$a = $this->links;
		$img = $this->images;
		$input = $this->input;

		if(count($a)>0){
		    foreach($a as $link){
		        // inside of code tag
		        $input = str_replace($link['new'], htmlspecialchars($link['original'], ENT_HTML5|ENT_QUOTES), $input);
		        
		    }
		}
		if(count($img)>0){
		    foreach($img as $image){
		        // inside of code tag
		        $input = str_replace($image['new'], htmlspecialchars($image['original'], ENT_HTML5|ENT_QUOTES), $input);
		    }
		}

		// reload the document with MD run.
		$html = $this->html->load($input, true, false);
		if(count($html->find('a'))>0){
		    foreach($html->find('a') as $e){
		        if(stripos($e->href, 'javascript:')!==false){
		            // gets any links that aren't in code blocks and have javascript in them
		            $e->outertext = htmlspecialchars($e->outertext, ENT_HTML5|ENT_QUOTES);
		        } 
		    }
		}
		if(count($html->find('img'))>0){
		    foreach($html->find('img') as $e){
		        if(stripos($e->attr['src'], 'javascript:')!==false){
		            // gets any image sources that aren't in code blocks and have javascript in them
		            $e->outertext = htmlspecialchars($e->outertext, ENT_HTML5|ENT_QUOTES);
		        } 
		    }
		}

		$this->input = $html;
		return $html;
	}
}
?>